# [general]
# import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "Roboto Mono"
style = "Bold"

[font.bold_italic]
family = "Roboto Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Roboto Mono"
style = "Italic"

[font.normal]
family = "Roboto Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000

[window]
dynamic_title = true
opacity = 0.98
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 160
lines = 50

[window.padding]
x = 10
y = 10

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 1000  # en millisecondes (500ms = 0.5s)
blink_timeout = 0     # 0 = jamais éteindre
unfocused_hollow = true

[colors.primary]
background = "#0f0f0f"
foreground = "#f5f5f5"

[colors.normal]
red = "#f28f3b"    # Sert à LS_COLORS ex=01;31
blue = "#7aa2f7"   # Sert à di=01;34 si tu veux
cyan = "#94e2d5"   # Pour symlinks (ln=01;36)
yellow = "#f9e2af" # Pour archives (zip, tar, etc.)
